### ISSUE TITLE
Get current TV state

### ISSUE THREAD

**Issue by mateuszdrab** [joshjowen/script.json-cec#7]
Hi

I've been researching the possibility of determining the status of the connected TV and I know this can be done via cecclient however this makes Kodi lose control of the TV which I heavily use to control with the remote.

I was wondering if you could implement a feature in this plugin to retrieve the current device status so that I can query this via Kodi via Home Assistant and have a more reliable way of determining whether the TV is on (it's an old non-smart TV that doesn't even react to CEC standby command well, but it responds and reports its status well).

Thanks
Matt

**Comment by mattie47** [comment]
Hi @mateuszdrab 

Unfortunately this is not currently possible. This script can only take advantange of what is exposed to it via kodi.

Kodi currently only exposes the following CEC functions: CECActivateSource, CECStandby, and CECToggleState.

This can be found here: http://kodi.wiki/view/list_of_built-in_functions

So essentially kodi-core needs to expose the equivalent of "echo "pow 0" | cec-client -s -d 1"

Thanks,

Matt

**Comment by mateuszdrab** [comment]
Hey @mattie47 

I kinda realised that after I made the request as I had a look into the code of the script.

This means I'd probably have to raise a Kodi's feature request.

In the meantime I am monitoring the TV status via a smart wifi switch with power monitoring.

I guess we can mark this off as closed - I doubt Kodi will feature this function any time soon and to be honest I'm pretty shocked it doesn't have it already.

Thanks
Matt :)

**Comment by mattie47** [comment]
@mateuszdrab 

Yeah I've sadly spent hours trying to figure out a way of attempting what should be such a simple task. 

I thought of having a go at trying to add it into kodi but I just don't have the knowledge for where to begin. Other than looking at the variables for the other cec functions...

From what I've understood, kodi takes ownership of libcec and does all the other cool functions like allowing the ability to control kodi using your normal tv remote. 

At this point I've read two conflicting reasons for why we can't use cec-client separately. 

- The most common reason I've read is because only one process can control the cec functionality at a time. This seems plausible as I remember seeing something "terminate" in kodi debug when simultaneously executing cec-client. 

- Yesterday I read the issue is actually the TV gets confused, because cec-client seems to send a different identity to the TV. Kodi comes up as "kodi" however cec-client sends "recorder". So I thought about trying to test this theory but haven't come up with a method yet...I doubt this is the case..

It's probably worth making a feature request on kodi. I'd certainly back it up, as there's good cause for this when a lot of people are now doing  home automation with apps such as home-assistant. 

Your smart wifi power plug is certainly a good workaround! 

Thanks,

Matt
